// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk1AuRTg6naSL97KiT8MJU1qPhVGueJHk',
    appId: '1:965264946682:web:1bc81424d942927e192043',
    messagingSenderId: '965264946682',
    projectId: 'courseconnectai',
    authDomain: 'courseconnectai.firebaseapp.com',
    storageBucket: 'courseconnectai.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSHiGhPx1isbqwmfTeDfFfnnTRJ09Juis',
    appId: '1:965264946682:android:83c792141a4a652d192043',
    messagingSenderId: '965264946682',
    projectId: 'courseconnectai',
    storageBucket: 'courseconnectai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk1WC-V1WJz7IVAJX3ksIhbvKIy2Zolko',
    appId: '1:965264946682:ios:de021906c19ce0c2192043',
    messagingSenderId: '965264946682',
    projectId: 'courseconnectai',
    storageBucket: 'courseconnectai.firebasestorage.app',
    iosBundleId: 'com.example.courseConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBk1WC-V1WJz7IVAJX3ksIhbvKIy2Zolko',
    appId: '1:965264946682:ios:de021906c19ce0c2192043',
    messagingSenderId: '965264946682',
    projectId: 'courseconnectai',
    storageBucket: 'courseconnectai.firebasestorage.app',
    iosBundleId: 'com.example.courseConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDk1AuRTg6naSL97KiT8MJU1qPhVGueJHk',
    appId: '1:965264946682:web:77033298aea36b0a192043',
    messagingSenderId: '965264946682',
    projectId: 'courseconnectai',
    authDomain: 'courseconnectai.firebaseapp.com',
    storageBucket: 'courseconnectai.firebasestorage.app',
  );
}
